- name: fan0
  path: /system/chassis/motherboard/fan0
  methods:
    - type: gpio
      key: 112
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000/1e78a000.i2c-bus/i2c-0/0-0049
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan0_0
        - fan0_1
  rpolicy:
    type: anyof

- name: fan1
  path: /system/chassis/motherboard/fan1
  methods:
    - type: gpio
      key: 113
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000/1e78a100.i2c-bus/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan1_0
        - fan1_1
  rpolicy:
    type: anyof

- name: fan2
  path: /system/chassis/motherboard/fan2
  methods:
    - type: gpio
      key: 114
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000/1e78a100.i2c-bus/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan2_0
        - fan2_1
  rpolicy:
    type: anyof

- name: fan3
  path: /system/chassis/motherboard/fan3
  methods:
    - type: gpio
      key: 115
      physpath: /sys/devices/platform/ahb/ahb:apb/ahb:apb:i2c@1e78a000/1e78a100.i2c-bus/i2c-3/3-0060
      devpath: /dev/input/by-path/platform-gpio-keys-polled-event
    - type: tach
      sensors:
        - fan3_0
        - fan3_1
  rpolicy:
    type: anyof
